### ISSUE TITLE
PUT behaves like PATCH

### ISSUE THREAD

**Issue by MichaelKetchel** [gregschmit/rails-rest-framework#28]
Issuing an update to a record via PUT behaves like PATCH,  updating only the sent properties instead of completely replacing the record as would be expected. This mostly manifests when a nullable field was not originally null, but is desired to be nulled, and a PUT with new property values is sent without a null for that property.

Potentially consider a way to make PUT behave as expected, or indicate that PUT behaves like PATCH

**Comment by MichaelKetchel** [comment]
it may make sense to have the OPTIONS return just PATCH for the "update" member method, and PUT as a "replace" method if supported?

**Comment by gregschmit** [comment]
Since Rails routes `PUT` and `PATCH` to the `update` action, I don't think I want to stray from that convention as it may be unintuitive for our users.

However, I think this could be resolved with an optional (and disabled by default) option (maybe `put_replace`) to have the default `update` action detect if the request method is `PUT` and either set the unspecified columns to `nil` (or their default value?). IIRC, Django REST Framework sets fields that are not passed to `None` for `update` action, but not `partial_update` action

**Comment by gregschmit** [comment]
I am not going to add this option because the user of this library can trivially overload the `update` action to achieve this behavior. If this becomes an issue again, I'll re-evaluate.
